[manifest]
version = "1.0.0"
dump_lua = true
priority = 69

# Add unique count

[[patches]] 
[patches.pattern]
target = "main.lua"
match_indent = true
pattern = "modded and {"
position = "before"
payload = '''
Cartomancer.add_view_deck_ui(unplayed_only), -- Cartomancer Steamodded 0.9.8 compatibility'''
